IDS, = glob_wildcards("{id}.fas")

rule all:
    input:
        expand("{id}.fas.orf.revalign",id=IDS)

rule longorf:
    input:
        "{d1}"
    output:
        temp("{d1}.orf")
    shell:
        "./longorf.sh {input} > {output}"

rule translate:
    input:
        "{d1}"
    output:
        temp("{d1}.aa")
    shell:
        "./translate.sh {input} > {output}"

rule align:
    input:
        "{d1}"
    output:
        temp("{d1}.align")
    shell:
        "mafft {input} > {output}"

rule pal2nal:
    input:
        ["{d1}","{d1}.aa.align"]
    output:
        "{d1}.revalign"
    shell:
        "perl pal2nal.pl {input[1]}  {input[0]} -output fasta > {output}"
