library(ape)
print("Please enter the name of the FASTA file for loading.")
f <- read.FASTA(file.choose())
print(f)
d <- dist.dna(f,model="F84")
p <- nj(d)
print(p)
p$node.label <- boot.phylo(p,as.matrix(f),function(x) nj(dist.dna(x, model='F84')))
print("Please name of the TRE file for saving.")
write.tree(p,file.choose())
